language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- curl https://commbank.artifactoryonline.com/commbank/binaries/ci/ci-$CI_VERSION.tar.gz | tar xz
- ci/sbt-ci-setup.sh
- ci/sbt-ci-setup-version.sh
- cp /etc/sbt/sbtopts .sbtopts; echo "-Dsbt.global.base=$TRAVIS_BUILD_DIR/ci" >> .sbtopts
script:
- sbt test package assembly
  && ci/sbt-ci-deploy.sh maven http://commbank.artifactoryonline.com/commbank ext-releases-local
  && ci/sbt-ci-build-doc.sh https://commbank.github.io/ https://github.com/CommBank/parlour/
  && ci/ci-push-branch.sh gh-pages
after_script:
- rm -rf ci
env:
  global:
  - CI_VERSION=3.2.2-20160718231250-50a210b
  - secure: hHSykHBWyIHK1o4ao48FXQIqv7xHYS9zRpS35r9jvBxFJ6uWCtcSh9TlHEx8xwvxRkf7uO1Obkn96nSNkujFvT5aZTEynEQx5GM+QqvzuR7f7WeoMsAQA4UrZACapRgS4tKPn6bbVmFkJ6XmZ0BBCvC+SOw0R4Vl9Jpyt40bIMs=
  - secure: c6wZgIToaP52YvHWzCjO8d+pFysnowWljBQnC5HNsYaLOb3IjNLSJjrAi8T2aWm2mPZk4KeLup55BF0IRsBSlgSrmyp9hMDZ+09r/zq52xUgkKSNjhtPa8I0GuQPr9n0Ku8M4JCA5ejcVdNFpIdo4BAkSQtZ9Nes6/n/MEDFNwg=
before_install:
- openssl aes-256-cbc -K $encrypted_a7cf6d2ecbdf_key -iv $encrypted_a7cf6d2ecbdf_iv
  -in .ci/deploy-key.enc -out .ci/deploy-key.pem -d
